library(lubridate)
powerdata <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
powerdata$Date <- dmy(powerdata$Date)
powerdata <- subset(powerdata, (Date == "2007-02-01") | (Date == "2007-02-02"))
powerdata$DateTime <- as.POSIXct(paste(powerdata$Date, powerdata$Time), format="%Y-%m-%d %H:%M:%S")
png("plot3.png")
par(mar = c(2,4,4,2))
plot(powerdata$DateTime, powerdata$Sub_metering_1, type = "l", ylab = "Energy sub metering")
lines(powerdata$DateTime, powerdata$Sub_metering_2, col = "red")
lines(powerdata$DateTime, powerdata$Sub_metering_3, col = "blue")
legend(legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), x = "topright", col = c("black", "red", "blue"), lty = 1)
dev.off()