library(lubridate)
powerdata <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
powerdata$Date <- dmy(powerdata$Date)
powerdata <- subset(powerdata, (Date == "2007-02-01") | (Date == "2007-02-02"))
powerdata$DateTime <- as.POSIXct(paste(powerdata$Date, powerdata$Time), format="%Y-%m-%d %H:%M:%S")
png("plot2.png")
par(mar = c(2,4,4,2))
plot(powerdata$DateTime, powerdata$Global_active_power, type = "l", xlab = " ", ylab = "Global Active Power (kilowatts)")
dev.off()